<?php
requireAdmin();$pdo=db();$p=pfx();$user=currentUser();$activePage='blog';$pageTitle='Blog Posts';
if($_SERVER['REQUEST_METHOD']==='POST'&&verifyCsrf()){$a=$_POST['action']??'';$id=(int)($_POST['id']??0);$sl=strtolower(trim(preg_replace('/[^a-z0-9]+/i','-',$_POST['title']??''),'-'));
if($a==='save'){if($id)$pdo->prepare("UPDATE `{$p}blog_posts` SET title=?,slug=?,content=?,excerpt=?,category=?,tags=?,featured_image=?,meta_title=?,meta_desc=?,status=?,updated_at=NOW() WHERE id=?")->execute([$_POST['title'],$sl,$_POST['content']??'',$_POST['excerpt']??'',$_POST['category']??'',$_POST['tags']??'',$_POST['featured_image']??'',$_POST['meta_title']??'',$_POST['meta_desc']??'',$_POST['status'],$id]);
else $pdo->prepare("INSERT INTO `{$p}blog_posts`(title,slug,content,excerpt,category,tags,featured_image,meta_title,meta_desc,status,author_id,created_at)VALUES(?,?,?,?,?,?,?,?,?,?,?,NOW())")->execute([$_POST['title'],$sl,$_POST['content']??'',$_POST['excerpt']??'',$_POST['category']??'',$_POST['tags']??'',$_POST['featured_image']??'',$_POST['meta_title']??'',$_POST['meta_desc']??'',$_POST['status'],$user['id']]);
redirect('/admin/blog');}
if($a==='delete'){$pdo->prepare("DELETE FROM `{$p}blog_posts` WHERE id=?")->execute([$id]);redirect('/admin/blog');}}
try{$posts=$pdo->query("SELECT b.*,u.name AS author FROM `{$p}blog_posts` b LEFT JOIN `{$p}users` u ON u.id=b.author_id ORDER BY b.created_at DESC")->fetchAll();}catch(Exception $e){$posts=[];}
ob_start();?>
<div class="ph"><div><div class="pt">Blog Posts</div></div><button class="btn bp" onclick="document.getElementById('bmid').value=0;document.getElementById('bmform').reset();oM('bmo')">+ New Post</button></div>
<div class="panel"><div class="tw"><table><thead><tr><th>TITLE</th><th>CATEGORY</th><th>AUTHOR</th><th>VIEWS</th><th>STATUS</th><th>DATE</th><th>ACTIONS</th></tr></thead><tbody>
<?php foreach($posts as $post):?><tr>
<td><div class="tdp"><?=e($post['title'])?></div><div class="tdm">/blog/<?=e($post['slug'])?></div></td>
<td class="tdm"><?=e($post['category']??'—')?></td><td class="tdm"><?=e($post['author']??'—')?></td>
<td><?=(int)$post['views']?></td><td><?=badge($post['status'])?></td>
<td class="tdm"><?=formatDate($post['created_at'])?></td>
<td><div class="tda"><button class="btn bs bxs" onclick="editPost(<?=htmlspecialchars(json_encode($post),ENT_QUOTES)?>)">Edit</button>
<?php if($post['status']==='published'):?><a href="<?=e(appUrl())?>/blog/<?=e($post['slug'])?>" target="_blank" class="btn bi bxs">↗</a><?php endif;?>
<form method="post" style="display:inline" onsubmit="return confirm('Delete?')"><input type="hidden" name="_token" value="<?=e(csrf())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=(int)$post['id']?>"><button class="btn bd bxs">✕</button></form>
</div></td></tr><?php endforeach;if(empty($posts)):?><tr><td colspan="7" style="text-align:center;padding:2rem;color:var(--mist)">No posts</td></tr><?php endif;?>
</tbody></table></div></div>
<?php $pageContent=ob_get_clean();
$modals='<div class="mo" id="bmo" style="align-items:flex-start;padding-top:2rem"><div class="mw mwl"><div class="mh"><div class="mt" id="bmtitle">New Post</div><button class="mc" onclick="cM(\'bmo\')">✕</button></div><div class="mb"><form method="post" id="bmform"><input type="hidden" name="_token" value="'.csrf().'"><input type="hidden" name="action" value="save"><input type="hidden" name="id" id="bmid" value="0"><div style="display:grid;grid-template-columns:1fr 1fr;gap:.7rem"><div class="fg"><label class="fl">TITLE</label><input type="text" name="title" id="bm_t" class="fc" required></div><div class="fg"><label class="fl">STATUS</label><select name="status" id="bm_st" class="fc"><option value="draft">Draft</option><option value="published">Published</option></select></div><div class="fg"><label class="fl">CATEGORY</label><input type="text" name="category" id="bm_c" class="fc"></div><div class="fg"><label class="fl">TAGS</label><input type="text" name="tags" id="bm_tg" class="fc"></div></div><div class="fg"><label class="fl">FEATURED IMAGE URL</label><input type="url" name="featured_image" id="bm_img" class="fc"></div><div class="fg"><label class="fl">EXCERPT</label><textarea name="excerpt" id="bm_ex" class="fc" rows="2"></textarea></div><div class="fg"><label class="fl">CONTENT (HTML supported)</label><textarea name="content" id="bm_con" class="fc" rows="12"></textarea></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:.7rem"><div class="fg"><label class="fl">META TITLE</label><input type="text" name="meta_title" id="bm_mt" class="fc"></div><div class="fg"><label class="fl">META DESC</label><input type="text" name="meta_desc" id="bm_md" class="fc"></div></div><div class="mf"><button type="button" class="btn bs" onclick="cM(\'bmo\')">Cancel</button><button type="submit" class="btn bp">Save Post</button></div></form></div></div></div>';
$js='<script>function editPost(p){document.getElementById("bmtitle").textContent="Edit Post";document.getElementById("bmid").value=p.id;document.getElementById("bm_t").value=p.title||"";document.getElementById("bm_st").value=p.status||"draft";document.getElementById("bm_c").value=p.category||"";document.getElementById("bm_tg").value=p.tags||"";document.getElementById("bm_img").value=p.featured_image||"";document.getElementById("bm_ex").value=p.excerpt||"";document.getElementById("bm_con").value=p.content||"";document.getElementById("bm_mt").value=p.meta_title||"";document.getElementById("bm_md").value=p.meta_desc||"";oM("bmo");}</script>';
include LB_ROOT.'/app/views/layouts/admin_wrap.php';
