<?php
requireLogin();$user=currentUser();$activePage='seo_report';$pageTitle='AI SEO Report';
ob_start();?>
<style>
.rep-section{background:var(--card);border:1px solid var(--border);border-radius:4px;overflow:hidden;margin-bottom:.9rem}
.rep-head{display:flex;align-items:center;justify-content:space-between;padding:.75rem 1rem;border-bottom:1px solid var(--border);background:rgba(255,255,255,.02)}
.rep-body{padding:1rem;font-size:.72rem;line-height:1.85;white-space:pre-wrap;word-wrap:break-word}
</style>

<div class="ph"><div><div class="pt">📊 AI SEO Monthly Report</div><div class="ps">Get a complete professional SEO report — auto-generated by AI</div></div>
<div class="pa"><button class="btn bs bsm" onclick="printReport()" id="printBtn" style="display:none">🖨 Print / PDF</button></div></div>

<div class="panel" style="margin-bottom:.9rem"><div class="pnb">
  <div style="display:grid;grid-template-columns:1fr 1fr 1fr auto;gap:.6rem;align-items:end">
    <div class="fg" style="margin-bottom:0"><label class="fl">YOUR DOMAIN</label><input type="text" id="rpDomain" class="fc" placeholder="yoursite.com" required></div>
    <div class="fg" style="margin-bottom:0"><label class="fl">REPORT PERIOD</label>
      <select id="rpPeriod" class="fc"><option>Last 30 Days</option><option>Last 90 Days</option><option>Last 6 Months</option><option>Year to Date</option></select>
    </div>
    <div class="fg" style="margin-bottom:0"><label class="fl">REPORT TYPE</label>
      <select id="rpType" class="fc"><option value="full">Full SEO Report</option><option value="technical">Technical Only</option><option value="content">Content Performance</option><option value="links">Backlink Report</option><option value="client">Client Report (Agency)</option></select>
    </div>
    <button class="btn bp" onclick="generateReport()" id="rpBtn" style="height:40px">📊 Generate →</button>
  </div>
  <div class="fg" style="margin-top:.7rem;margin-bottom:0"><label class="fl">ADDITIONAL CONTEXT (optional)</label>
    <input type="text" id="rpContext" class="fc" placeholder="e.g. 'We published 4 posts', 'We built 12 guest posts', 'Rankings dropped week 2'...">
  </div>
</div></div>

<div id="rpLoading" style="display:none;text-align:center;padding:3rem">
  <div style="font-size:2rem;animation:sp3 .9s linear infinite;display:inline-block;color:var(--acid);margin-bottom:.8rem">📊</div>
  <div style="font-family:Syne,sans-serif;font-weight:700;margin-bottom:.3rem">Generating your SEO report...</div>
  <div style="font-size:.65rem;color:var(--mist)">This takes 20-30 seconds — AI is writing a full report</div>
</div>

<div id="rpOutput" style="display:none"></div>

<script>
const API='https://api.anthropic.com/v1/messages';
async function generateReport(){
  var dom=document.getElementById('rpDomain').value.trim();
  if(!dom)return alert('Enter your domain');
  var period=document.getElementById('rpPeriod').value;
  var type=document.getElementById('rpType').value;
  var ctx=document.getElementById('rpContext').value;

  document.getElementById('rpBtn').disabled=true;
  document.getElementById('rpLoading').style.display='block';
  document.getElementById('rpOutput').style.display='none';
  document.getElementById('printBtn').style.display='none';

  var sysPrompts={
    full:'You are a senior SEO analyst writing a professional monthly report. Write in a professional, data-driven style.',
    client:'You are writing a white-label SEO report for an agency client. Use friendly, non-technical language. Focus on business outcomes.',
    technical:'You are a technical SEO specialist writing a detailed technical audit report.',
    content:'You are a content SEO strategist writing a content performance report.',
    links:'You are a link building specialist writing a backlink analysis report.'
  };

  var mainPrompt=`Generate a complete, professional SEO report for ${dom}.
Period: ${period} | Type: ${type} report
${ctx?'Additional context: '+ctx:''}

Write a full, publication-ready SEO report with these sections. Be specific with realistic numbers and insights.

Format with clear headers using ## for sections and ### for subsections. Include:

## Executive Summary
(3-4 sentence overview of performance, biggest wins, and priority concerns)

## Key Metrics Overview
(Table format: Organic Traffic estimate, Keywords ranking, Domain Authority estimate, Backlinks estimate, Core Web Vitals status)

## Ranking Performance
(Top keywords, ranking changes, new rankings gained/lost, featured snippets)

## Technical SEO Status
(Site health, crawlability, page speed, mobile-friendliness, structured data)

## Content Performance
(Best performing content, content gaps, recommendations for new content)

## Backlink Analysis
(New/lost backlinks, referring domains, link quality assessment, link building activity)

## Competitor Movements
(What competitors are doing, ranking changes, threats and opportunities)

## Next Month Action Plan
(5-7 prioritized actions with expected impact)

## Growth Projections
(Conservative/optimistic traffic projections for next 90 days)

Write as if you have real data from Analytics and Search Console. Be specific with estimated numbers.`;

  try{
    var r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},
      body:JSON.stringify({model:'claude-sonnet-4-20250514',max_tokens:2000,
        system:sysPrompts[type]||sysPrompts.full,
        messages:[{role:'user',content:mainPrompt}]})});
    var d=await r.json();
    var text=d.content?.map(b=>b.text||'').join('')||'';
    renderReport(text,dom,period);
  }catch(e){document.getElementById('rpOutput').innerHTML='<div class="al al-e">'+e.message+'</div>';document.getElementById('rpOutput').style.display='block';}
  document.getElementById('rpBtn').disabled=false;
  document.getElementById('rpLoading').style.display='none';
}

function renderReport(text,dom,period){
  // Parse markdown-ish into HTML
  var lines=text.split('\n');
  var html=`<div id="reportDoc" style="background:var(--card);border:1px solid var(--border);border-radius:4px;overflow:hidden">`;
  html+=`<div style="background:linear-gradient(135deg,rgba(184,255,60,.08),rgba(84,160,255,.05));border-bottom:1px solid rgba(184,255,60,.15);padding:1.5rem">
    <div style="font-family:Syne,sans-serif;font-weight:800;font-size:1.2rem;margin-bottom:.3rem">SEO Performance Report</div>
    <div style="font-size:.68rem;color:var(--mist)">${dom} — ${period} — Generated ${new Date().toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})}</div>
    <div style="margin-top:.6rem;display:flex;gap:.5rem;flex-wrap:wrap">
      <span class="bdg b-success">✓ Complete Report</span>
      <span class="bdg b-info">AI-Generated</span>
    </div>
  </div>`;
  html+=`<div style="padding:1.4rem;font-size:.74rem;line-height:1.85">`;

  var inSection=false;
  lines.forEach(line=>{
    if(line.startsWith('## ')){
      if(inSection)html+='</div></div>';
      html+=`<div style="margin-bottom:.9rem;border:1px solid var(--border);border-radius:4px;overflow:hidden">
        <div style="background:rgba(255,255,255,.02);border-bottom:1px solid var(--border);padding:.6rem .9rem">
          <div style="font-family:Syne,sans-serif;font-weight:700;font-size:.82rem">${line.replace('## ','')}</div>
        </div><div style="padding:.85rem">`;
      inSection=true;
    }else if(line.startsWith('### ')){
      html+=`<div style="font-family:Syne,sans-serif;font-weight:700;color:var(--acid);margin:.6rem 0 .3rem;font-size:.72rem">${line.replace('### ','')}</div>`;
    }else if(line.match(/^\|/)){
      html+=`<div style="font-family:monospace;font-size:.66rem;color:${line.includes('---')?'transparent':'var(--mist)'};padding:.18rem 0">${line.replace(/\|/g,'<span style="color:rgba(255,255,255,.15)">│</span>')}</div>`;
    }else if(line.match(/^[-*] /)){
      html+=`<div style="display:flex;gap:.4rem;padding:.18rem 0"><span style="color:var(--acid)">→</span><span>${line.replace(/^[-*] /,'')}</span></div>`;
    }else if(line.match(/^\d+\./)){
      html+=`<div style="display:flex;gap:.4rem;padding:.18rem 0"><span style="color:var(--acid);font-weight:700;min-width:1.2rem">${line.match(/^\d+/)[0]}.</span><span>${line.replace(/^\d+\.\s*/,'')}</span></div>`;
    }else if(line.startsWith('**')&&line.endsWith('**')){
      html+=`<div style="font-family:Syne,sans-serif;font-weight:700;margin:.3rem 0 .1rem">${line.replace(/\*\*/g,'')}</div>`;
    }else if(line.trim()){
      html+=`<p style="margin:.2rem 0;color:var(--mist)">${line.replace(/\*\*(.*?)\*\*/g,'<strong style="color:var(--paper)">$1</strong>')}</p>`;
    }
  });
  if(inSection)html+='</div></div>';
  html+='</div></div>';

  document.getElementById('rpOutput').innerHTML=html;
  document.getElementById('rpOutput').style.display='block';
  document.getElementById('printBtn').style.display='block';
  document.getElementById('rpOutput').scrollIntoView({behavior:'smooth'});
}

function printReport(){
  var content=document.getElementById('reportDoc').innerHTML;
  var w=window.open('','_blank');
  w.document.write('<html><head><title>SEO Report</title><style>body{font-family:Georgia,serif;padding:40px;max-width:900px;margin:0 auto;line-height:1.7;color:#111}h2{color:#1a1a2e;border-bottom:2px solid #b8ff3c;padding-bottom:8px}h3{color:#333}table{width:100%;border-collapse:collapse}td,th{border:1px solid #ddd;padding:6px 10px;text-align:left}.bdg{background:#eee;padding:2px 8px;border-radius:3px;font-size:11px;font-weight:bold}.b-success{background:#d4edda;color:#155724}.b-info{background:#d1ecf1;color:#0c5460}@media print{body{padding:20px}}</style></head><body>'+content+'<script>window.print();<\/script></body></html>');
  w.document.close();
}
</script>
<?php $pageContent=ob_get_clean();include LB_ROOT.'/app/views/layouts/client_wrap.php';
