<?php
requireAdmin();$pdo=db();$p=pfx();$user=currentUser();$activePage='pages';$pageTitle='Pages';
if($_SERVER['REQUEST_METHOD']==='POST'&&verifyCsrf()){$a=$_POST['action']??'';$id=(int)($_POST['id']??0);if($a==='save'){if($id)$pdo->prepare("UPDATE `{$p}pages` SET title=?,slug=?,content=?,meta_title=?,meta_desc=?,status=?,updated_at=NOW() WHERE id=?")->execute([$_POST['title'],$_POST['slug'],$_POST['content']??'',$_POST['meta_title']??'',$_POST['meta_desc']??'',$_POST['status'],$id]);else $pdo->prepare("INSERT INTO `{$p}pages`(title,slug,content,meta_title,meta_desc,status,created_at)VALUES(?,?,?,?,?,?,NOW())")->execute([$_POST['title'],$_POST['slug'],$_POST['content']??'',$_POST['meta_title']??'',$_POST['meta_desc']??'',$_POST['status']]);redirect('/admin/pages');}if($a==='delete'){$pdo->prepare("DELETE FROM `{$p}pages` WHERE id=?")->execute([$id]);redirect('/admin/pages');}}
try{$pages=$pdo->query("SELECT * FROM `{$p}pages` ORDER BY id")->fetchAll();}catch(Exception $e){$pages=[];}
ob_start();?>
<div class="ph"><div><div class="pt">Pages</div></div><button class="btn bp" onclick="document.getElementById('pgid').value=0;document.getElementById('pgform').reset();oM('pgmo')">+ New Page</button></div>
<div class="panel"><div class="tw"><table><thead><tr><th>TITLE</th><th>SLUG</th><th>STATUS</th><th>ACTIONS</th></tr></thead><tbody>
<?php foreach($pages as $pg):?><tr>
<td class="tdp"><?=e($pg['title'])?></td><td class="tdm">/<?=e($pg['slug'])?></td>
<td><?=badge($pg['status'])?></td>
<td><div class="tda"><button class="btn bs bxs" onclick="editPage(<?=htmlspecialchars(json_encode($pg),ENT_QUOTES)?>)">Edit</button>
<form method="post" style="display:inline" onsubmit="return confirm('Delete?')"><input type="hidden" name="_token" value="<?=e(csrf())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=(int)$pg['id']?>"><button class="btn bd bxs">✕</button></form>
</div></td></tr><?php endforeach;?></tbody></table></div></div>
<?php $pageContent=ob_get_clean();
$modals='<div class="mo" id="pgmo" style="align-items:flex-start;padding-top:2rem"><div class="mw mwl"><div class="mh"><div class="mt">Page Editor</div><button class="mc" onclick="cM(\'pgmo\')">✕</button></div><div class="mb"><form method="post" id="pgform"><input type="hidden" name="_token" value="'.csrf().'"><input type="hidden" name="action" value="save"><input type="hidden" name="id" id="pgid" value="0"><div style="display:grid;grid-template-columns:1fr 1fr;gap:.7rem"><div class="fg"><label class="fl">TITLE</label><input type="text" name="title" id="pg_t" class="fc" required></div><div class="fg"><label class="fl">SLUG</label><input type="text" name="slug" id="pg_s" class="fc" required></div></div><div class="fg"><label class="fl">CONTENT (HTML)</label><textarea name="content" id="pg_c" class="fc" rows="12"></textarea></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:.7rem"><div class="fg"><label class="fl">META TITLE</label><input type="text" name="meta_title" id="pg_mt" class="fc"></div><div class="fg"><label class="fl">META DESC</label><input type="text" name="meta_desc" id="pg_md" class="fc"></div></div><div class="fg"><label class="fl">STATUS</label><select name="status" id="pg_st" class="fc"><option value="published">Published</option><option value="draft">Draft</option></select></div><div class="mf"><button type="button" class="btn bs" onclick="cM(\'pgmo\')">Cancel</button><button type="submit" class="btn bp">Save Page</button></div></form></div></div></div>';
$js='<script>function editPage(p){document.getElementById("pgid").value=p.id;document.getElementById("pg_t").value=p.title||"";document.getElementById("pg_s").value=p.slug||"";document.getElementById("pg_c").value=p.content||"";document.getElementById("pg_mt").value=p.meta_title||"";document.getElementById("pg_md").value=p.meta_desc||"";document.getElementById("pg_st").value=p.status||"published";oM("pgmo");}</script>';
include LB_ROOT.'/app/views/layouts/admin_wrap.php';
