<?php
requireAdmin();$pdo=db();$p=pfx();$user=currentUser();$activePage='publishers';$pageTitle='Publisher Directory';
if($_SERVER['REQUEST_METHOD']==='POST'&&verifyCsrf()){$a=$_POST['action']??'';$id=(int)($_POST['id']??0);
if($a==='save'){$d=[$_POST['domain'],$_POST['niche'],$_POST['da'],$_POST['dr'],$_POST['traffic'],(float)$_POST['price'],$_POST['link_type'],$_POST['language'],$_POST['country'],(int)($_POST['is_featured']??0),(int)$_POST['status']];
if($id)$pdo->prepare("UPDATE `{$p}publishers` SET domain=?,niche=?,da=?,dr=?,traffic=?,price=?,link_type=?,language=?,country=?,is_featured=?,status=? WHERE id=?")->execute(array_merge($d,[$id]));
else $pdo->prepare("INSERT INTO `{$p}publishers`(domain,niche,da,dr,traffic,price,link_type,language,country,is_featured,status,created_at)VALUES(?,?,?,?,?,?,?,?,?,?,?,NOW())")->execute($d);redirect('/admin/publishers');}
if($a==='delete'){$pdo->prepare("DELETE FROM `{$p}publishers` WHERE id=?")->execute([$id]);redirect('/admin/publishers');}}
try{$pubs=$pdo->query("SELECT * FROM `{$p}publishers` ORDER BY is_featured DESC,da DESC")->fetchAll();}catch(Exception $e){$pubs=[];}
ob_start();?>
<div class="ph"><div><div class="pt">Publisher Directory</div><div class="ps"><?=count($pubs)?> total</div></div>
<div class="pa"><a href="<?=e(appUrl())?>/publishers" target="_blank" class="btn bs bsm">↗ View Public</a><button class="btn bp" onclick="document.getElementById('pmid').value=0;document.getElementById('pmform').reset();oM('pmmo')">+ Add Publisher</button></div></div>
<div class="panel"><div class="tw"><table><thead><tr><th>DOMAIN</th><th>NICHE</th><th>DA</th><th>DR</th><th>TRAFFIC</th><th>PRICE</th><th>TYPE</th><th>FEATURED</th><th>STATUS</th><th>ACTIONS</th></tr></thead><tbody>
<?php foreach($pubs as $pub):?><tr>
<td class="tdp"><?=e($pub['domain'])?></td><td class="tdm"><?=e($pub['niche']??'')?></td>
<td><strong style="color:var(--blue)"><?=(int)$pub['da']?></strong></td><td><strong style="color:var(--purple)"><?=(int)$pub['dr']?></strong></td>
<td class="tdm"><?=e($pub['traffic']??'—')?></td><td style="color:var(--acid);font-weight:700"><?=moneyFmt($pub['price'])?></td>
<td class="tdm"><?=e(str_replace('_',' ',$pub['link_type']??''))?></td>
<td><?=$pub['is_featured']?'<span style="color:var(--acid)">★</span>':'—'?></td>
<td><?=badge($pub['status']?'active':'inactive')?></td>
<td><div class="tda"><button class="btn bs bxs" onclick="editPub(<?=htmlspecialchars(json_encode($pub),ENT_QUOTES)?>)">Edit</button>
<form method="post" style="display:inline" onsubmit="return confirm('Delete?')"><input type="hidden" name="_token" value="<?=e(csrf())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=(int)$pub['id']?>"><button class="btn bd bxs">✕</button></form>
</div></td></tr><?php endforeach;?></tbody></table></div></div>
<?php $pageContent=ob_get_clean();
$modals='<div class="mo" id="pmmo"><div class="mw mwl"><div class="mh"><div class="mt">Publisher</div><button class="mc" onclick="cM(\'pmmo\')">✕</button></div><div class="mb"><form method="post" id="pmform"><input type="hidden" name="_token" value="'.csrf().'"><input type="hidden" name="action" value="save"><input type="hidden" name="id" id="pmid" value="0"><div style="display:grid;grid-template-columns:1fr 1fr;gap:.7rem"><div class="fg"><label class="fl">DOMAIN</label><input type="text" name="domain" id="pmdomain" class="fc" required></div><div class="fg"><label class="fl">NICHE</label><input type="text" name="niche" id="pmniche" class="fc"></div><div class="fg"><label class="fl">DA</label><input type="number" name="da" id="pmda" class="fc" min="0" max="100" value="0"></div><div class="fg"><label class="fl">DR</label><input type="number" name="dr" id="pmdr" class="fc" min="0" max="100" value="0"></div><div class="fg"><label class="fl">TRAFFIC/MO</label><input type="text" name="traffic" id="pmtr" class="fc" placeholder="e.g. 50K/mo"></div><div class="fg"><label class="fl">PRICE</label><input type="number" name="price" id="pmprice" class="fc" step="0.01" required></div><div class="fg"><label class="fl">TYPE</label><select name="link_type" id="pmtype" class="fc"><option value="guest_post">Guest Post</option><option value="niche_edit">Niche Edit</option><option value="homepage">Homepage Link</option></select></div><div class="fg"><label class="fl">LANGUAGE</label><input type="text" name="language" id="pmlang" class="fc" value="English"></div><div class="fg"><label class="fl">COUNTRY</label><input type="text" name="country" id="pmcountry" class="fc" value="US"></div><div class="fg"><label class="fl">STATUS</label><select name="status" id="pmstatus" class="fc"><option value="1">Active</option><option value="0">Inactive</option></select></div><div class="fg"><label class="fl">FEATURED</label><select name="is_featured" id="pmfeat" class="fc"><option value="0">No</option><option value="1">Yes</option></select></div></div><div class="mf"><button type="button" class="btn bs" onclick="cM(\'pmmo\')">Cancel</button><button type="submit" class="btn bp">Save</button></div></form></div></div></div>';
$js='<script>function editPub(p){document.getElementById("pmid").value=p.id;document.getElementById("pmdomain").value=p.domain||"";document.getElementById("pmniche").value=p.niche||"";document.getElementById("pmda").value=p.da||0;document.getElementById("pmdr").value=p.dr||0;document.getElementById("pmtr").value=p.traffic||"";document.getElementById("pmprice").value=p.price||"";document.getElementById("pmtype").value=p.link_type||"guest_post";document.getElementById("pmlang").value=p.language||"English";document.getElementById("pmcountry").value=p.country||"US";document.getElementById("pmstatus").value=p.status||1;document.getElementById("pmfeat").value=p.is_featured||0;oM("pmmo");}</script>';
include LB_ROOT.'/app/views/layouts/admin_wrap.php';
